#!/bin/bash
set -ex

# DockerHub Automated Build를 위한 Custom Environment Hook
# 빌드 시에 사용자 환경변수를 전달한다

docker build \
    --build-arg API_KEY="${API_KEY}" \
    --build-arg API_SECRET="${API_SECRET}" \
    --build-arg ACCESS_TOKEN="${ACCESS_TOKEN}" \
    --build-arg ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}" \
    --build-arg TOPIC="${TOPIC}" \
    --build-arg BROKER="${BROKER}" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
